### ISSUE TITLE
Issue: The Pause Buttons..

### ISSUE THREAD

**Issue by AnshSinghSonkhia** [AnshSinghSonkhia/40Pie-Music-Player-Website#10]
The small pause buttons in front of each song names must change to play when the song end or the next song is played or the song is paused.

**Comment by ahmedsilat44** [comment]
A fix for this when the song ends is that the progress  should be tracked and when it is 100% the icon should be switched.

**Comment by Kingsman44** [comment]
@AnshSinghSonkhia check my pull request
