### ISSUE TITLE
Add about us page

### ISSUE THREAD

**Issue by ola-nishant** [AnshSinghSonkhia/40Pie-Music-Player-Website#31]
I would like to add about us page, that matches the theme of the website and shows the idea behind it, please assign it to me and add hacktoberfest label

**Comment by AnshSinghSonkhia** [comment]
Hey @ola-nishant,
Could you please show the design type of about us page that you want to add?
Some Screenshot would work.....

**Comment by ompanchwate** [comment]
Hello, Can you assign this issue to me under Hacktoberfest 2022. I can develop attractive About Us page.

**Comment by ompanchwate** [comment]
Hello, Can you assign this issue to me under Hacktoberfest 2022. I can develop attractive About Us page.  My previous Work - https://hopetrustfoundation.netlify.app/

**Comment by ola-nishant** [comment]
> Hey @ola-nishant, Could you please show the design type of about us page that you want to add? Some Screenshot would work.....

i would use the same styling that you have used in the 40 pi app. i would also link the page to the navbar, add some content, and your socials like linkedin and your experience to it, i will add the screenshots in the pr, please assign it to me for now

**Comment by ola-nishant** [comment]
![Screenshot 2022-10-06 014600](https://user-images.githubusercontent.com/108128949/194154857-182c41e8-5346-44f5-9d65-aa45a38872ca.jpg)
this is how the about us page would look, the navbar is working as well, the data has been scraped from your github and linkedin, you can change it accordingly, of course, please add the hacktoberfest labels, so that i can push the code ( i also have the code for the footer after that as well , 😉)

**Comment by AnshSinghSonkhia** [comment]
> ![Screenshot 2022-10-06 014600](https://user-images.githubusercontent.com/108128949/194154857-182c41e8-5346-44f5-9d65-aa45a38872ca.jpg) this is how the about us page would look, the navbar is working as well, the data has been scraped from your github and linkedin, you can change it accordingly, of course, please add the hacktoberfest labels, so that i can push the code ( i also have the code for the footer after that as well , 😉)

Great work @ola-nishant Ji! Go for it.
