### ISSUE TITLE
Add More Songs

### ISSUE THREAD

**Issue by AnshSinghSonkhia** [AnshSinghSonkhia/40Pie-Music-Player-Website#6]
- [ ] Added Song - (**Song Name**).
- [ ] Added .mp3 Song File of the above Song.
- [ ] Added Code for this Song.
- [ ] Update index.html Code.

> **Note**
> Everyone can work on this issue, no need to be an assignee

**Comment by Aryangp** [comment]
hi i want to work on this issue pls assign this issue to me

**Comment by Siddhanthota** [comment]
Can you assign this to me?

**Comment by devhvrshu** [comment]
Hey Ansh, Can you assign this to me?

**Comment by AbhishekRP2002** [comment]
Hey there ! Can you assign this to me ?

**Comment by vaibhavmishra4g** [comment]
Could you assign me this?
