### ISSUE TITLE
I would like to add Replay Button

### ISSUE THREAD

**Issue by Shubhcs01** [AnshSinghSonkhia/40Pie-Music-Player-Website#8]

**Comment by AnshSinghSonkhia** [comment]
Describe your whole plan in detail @Shubhcs01.

**Comment by Shubhcs01** [comment]
I will add a Replay button in the music player below seek bar.
 It will appear when the current song ended, before that it'll not visible to user.
 It will allow the user to re-play the song again.

**Comment by AnshSinghSonkhia** [comment]
Hey @Shubhcs01,
In our website, once the song finishes, the next one plays. So, we don't want a replay button.

However, in another issue, we are working on a loop button feature. You can contribute in it.

Thanks.
